### ISSUE TITLE
'Close' Button doesn't work

### ISSUE THREAD

**Issue by astrorookie** [Darkempire78/Lyrics-Spicetify#1]
I love this! My only issue so far is that the X button I assume is meant to close the lyrics doesn't quite work, I have to hover my cursor just _below_ the X to get it to close it. 

https://user-images.githubusercontent.com/61162548/104827295-0045be80-5854-11eb-866c-93a1196be8ed.mp4

**Comment by clementwzk** [comment]
Thanks for the report! I already knew the issue, I will try to fix this tomorrow

**Comment by clementwzk** [comment]
It's very strange because when i remove the right alignment, the button works.
I already tried to change for flexbox but there is no change.

**Comment by clementwzk** [comment]
fixed
