### ISSUE TITLE
cant enable plugin

### ISSUE THREAD

**Issue by jakiisheep** [Darkempire78/Lyrics-Spicetify#2]
i know how its enabled, but I'm currently using dribbblish theme and cant click the arrow down button and enable the plugin, is there any way for me to enable it?

**Comment by jakiisheep** [comment]
https://raw.githubusercontent.com/Darkempire78/Lyrics-Spicetify/main/.github/Capture2.png (this)

**Comment by clementwzk** [comment]
Did you have run the `spicetify apply` line in your shell ?

**Comment by jakiisheep** [comment]
yes im talking about that im using the dribbblish theme and cant enable the plugin I have spicetidfy and everything applied

**Comment by clementwzk** [comment]
Works for me
![image](https://user-images.githubusercontent.com/50015928/106358215-f4093900-630a-11eb-832c-f165b7128a62.png)

**Comment by jakiisheep** [comment]
the thing is you havent installed the extension, when the extension is installed that button dissapears

**Comment by clementwzk** [comment]
Works with the extension
![image](https://user-images.githubusercontent.com/50015928/106358268-7265db00-630b-11eb-9ab4-9b9d2cbff49d.png)

**Comment by jakiisheep** [comment]
![image](https://user-images.githubusercontent.com/68562536/106358284-93c6c700-630b-11eb-9c43-dfe521656efd.png)
not for me..

**Comment by clementwzk** [comment]
You have not the arrow button ?

**Comment by jakiisheep** [comment]
yes

**Comment by clementwzk** [comment]
You can not go in the settings if the button is hiden ?

**Comment by jakiisheep** [comment]
yes ?

**Comment by clementwzk** [comment]
What is the exact theme name because we have not the same :/

**Comment by jakiisheep** [comment]
Dribbblish Nord Dark with modified colors

**Comment by jakiisheep** [comment]
https://github.com/morpheusthewhite/spicetify-themes/tree/master/Dribbblish

**Comment by jakiisheep** [comment]
i see the button here but idk

**Comment by Darkempire78** [comment]
send me a screenshot of the button items

**Comment by Darkempire78** [comment]
oh ok x)

**Comment by clementwzk** [comment]
can you give me a screenshot of your config file ?

**Comment by jakiisheep** [comment]
what one, user.css or colors.ini

**Comment by clementwzk** [comment]
No, the Spicetify config file
![image](https://user-images.githubusercontent.com/50015928/106358519-07b59f00-630d-11eb-85f3-102eda7983b6.png)

**Comment by sheeepdev** [comment]
![Uploading image.png…]()

**Comment by jakiisheep** [comment]
![image](https://user-images.githubusercontent.com/68562536/106358534-1b610580-630d-11eb-9929-d44ea7ab7ea2.png)

**Comment by jakiisheep** [comment]
wait should i enable lyric_always-show

**Comment by jakiisheep** [comment]
Wait that works but when i go to hover over the button it dissapears

**Comment by clementwzk** [comment]
If you do not see the settings button it's not caused by my plugin. Open an issue on the theme repository :/

**Comment by jakiisheep** [comment]
it works bro i changed it in the config.ini, but now the button disappeared, it showed and when I hovered it disseapeared and it wont show again

**Comment by clementwzk** [comment]
lyric_always_show is not linked with the plugin

**Comment by jakiisheep** [comment]
It is? when i enabled it it shows

**Comment by clementwzk** [comment]
I do not know what is this variable. 
Open an issue on the theme repository, you can also retry to apply your theme

**Comment by jakiisheep** [comment]
@Darkempire78 i found the solution! this element was hidden and I unhid it and now the button shows! 
![image](https://user-images.githubusercontent.com/68562536/106359522-a9d88580-6313-11eb-99e0-1085f5359690.png)

**Comment by clementwzk** [comment]
nice :D

**Comment by sheeepdev** [comment]
and is there a way to change the bg color of the lyrics menu? (unrelated to this issue)

**Comment by clementwzk** [comment]
Yes, change the line 58 of the `spotifyLyrics.js` file :         
```Javascript 
div.style.backgroundColor = "#111111";
```

**Comment by jakiisheep** [comment]
ok already found it :) thanks! trying to solve the issue with the close button now, I may find  solution who knows
