### ISSUE TITLE
UI Fixes

### ISSUE THREAD

**Issue by yougotwill** [Darkempire78/Lyrics-Spicetify#7]
Hi, firstly thanks for this awesome extension!

I made a couple fixes and changes to the UI. If you like it I will open a PR.

1. Updated the lyrics button to use an SVG icon so it's cleaner and takes less space (royalty free SVG used)
2. I removed most styling from the lyrics container so that it matches the users theme.
3. The lyrics container is now on the right hand side like the friend bar for consistency. 
4. You can now scroll in the lyrics container so you can see all the lyrics.
5. Not sure how but the close button now works again. This fixes https://github.com/Darkempire78/Lyrics-Spicetify/issues/1

Please see below for the changes in action. Excuse my custom theme.

## Dark Theme

https://user-images.githubusercontent.com/14887287/116988977-6f470600-acd1-11eb-98f9-6750406c1b3e.mp4

## Light Theme

https://user-images.githubusercontent.com/14887287/116988992-74a45080-acd1-11eb-8934-d8e9964e476b.mp4

If you like it then I'll make the PR as soon as possible. 😄

**Comment by clementwzk** [comment]
Thank you some much!
A PR is welcome 😀

**Comment by yougotwill** [comment]
Done 🚀
